### ISSUE TITLE
How to provision an IoT Agent

### ISSUE THREAD

**Issue by wmmihaa** [Fiware/tutorials.Getting-Started#16]
As I've been going through the tutorial (great postman samples btw), I got stuck on how to register an IoT Agent, meaning how do I get/generate tokens etc?

**Comment by jason-fox** [comment]
I assume that this issue should have been raised under the [IoT Agent tutorial](https://github.com/FIWARE/tutorials.IoT-Agent/issues). The **Getting Started** tutorial only includes the context broker.

Could you provide further details by raising a separate issue over there - it is unclear which tutorial and which step you are referring to and which token are you talking about.

**Comment by wmmihaa** [comment]
I (perhaps wrongly) assumed that the IoT Agent needed to be registered in the context broker prior to connecting to it...

**Comment by jason-fox** [comment]
The  IoT Agent registers itself with the context broker on startup using the `IOTA_CB_HOST` environment variable - An example can be found it the [docker-compose](https://github.com/FIWARE/tutorials.IoT-Agent/blob/0165714f3a9c61436e1c09897b71fefdd92b5f03/docker-compose.yml#L54)

Manual registration of commands is in the context broker is no longer necessary. Later versions of the IoT Agents are able automatically register devices into the context broker - see https://github.com/FIWARE/tutorials.IoT-Agent/issues/20 - the tutorial still keeps the redundant step at the moment.

**Comment by jason-fox** [comment]
**Closing** this issue, as further discussion should be raised against another tutorial.

**Comment by wmmihaa** [comment]
Sorry...for not understanding just yet...

I understand that there would be some environment variable pointing to the uri of the context broker, but surly there must be some provisioning process allowing the agent to connect?

I do appreciate your quick answers, and I apologize if they are stupid. I come from a background of AWS and Azure and assumes an IoT agent is the equivalent of a Thing/Device.

**Comment by jason-fox** [comment]
IoT Agents are not devices, they are a middleware which connects to devices. Basically you're confusing the two ports of the IoT Agent.

* The **North Port** of the IoT Agent speaks _NGSI_ and can connect to the context broker directly
* The **South Port** of the IoT Agent speaks _whatever-your-device-protocol/payload_ is and indeed does need to be provisioned.

The **South Port** can be kind of vague as well, as the IoT Agent-to-device communication does not necessarily have to be HTTP. If it is HTTP, the flow of HTTP requests is kind of obvious:

* Context Broker => IoT Agent => Device

But it could be that the IoT Agent is just listening to topics on an MQTT broker or accepting COAP requests from [LightweightM2M](https://github.com/telefonicaid/lightweightm2m-iotagent) or listening to a [LoRa server](https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN) or whatever.

Depending on your data flow you could also look at the [Node Red](https://github.com/FIWARE/node-red-contrib-FIWARE_official) connector.
