### ISSUE TITLE
Error when trying to use the `services` command on the NGSI-LD branch

### ISSUE THREAD

**Issue by bobeal** [Fiware/tutorials.Getting-Started#23]
Hi,

I am trying to use the Getting Started guide on the NGSI-LD branch and I have the following error when trying to launch the services:

```shell
tutorials.Getting-Started on  NGSI-LD [$]
➜  ./services orion
Stopping containers
Unable to parse logging level: compose
```

I have the same error when running `./services stop` or `./services create`.

Any idea?

**Comment by jason-fox** [comment]
You probably have an outdated version of docker-compose on your machine. The prerequisites in the documentation state 

 > Docker version 18.03 or higher and Docker Compose 1.21 or higher and upgrade if necessary.

When I run 

```console
docker-compose version
```

I get:

```text
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

And that is working fine.

**Comment by jason-fox** [comment]
If necessary run the following

```console
sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

**Comment by bobeal** [comment]
> You probably have an outdated version of docker-compose on your machine. The prerequisites in the documentation state
> 
> > Docker version 18.03 or higher and Docker Compose 1.21 or higher and upgrade if necessary.

Hmm, or more probably, a too recent one:

```
➜  docker-compose version
Docker Compose version v2.0.0-beta.6
```

and:

```
➜  docker --version
Docker version 20.10.7, build f0df350
```

I gonna look how I can fix that...

**Comment by jason-fox** [comment]
There is a workaround here: https://github.com/docker/compose-cli/issues/1891

**Comment by bobeal** [comment]
Yes, found this in the meantime. It woks after disabling docker-compose v2.

Thanks!
