### ISSUE TITLE
Services script removes all containers and volumes

### ISSUE THREAD

**Issue by thanospan** [Fiware/tutorials.Getting-Started#32]
The [stoppingContainers](https://github.com/FIWARE/tutorials.Getting-Started/blob/49a55a5d5d5e7163c60d60e825dfd2bc1eff50b3/services#L102) function in the services script does not filter based on labels and therefore removes all containers and volumes on the machine.

**Comment by jason-fox** [comment]
Fixed  3b4b8e3
