### ISSUE TITLE
Problem in file data-models/ngsi-context.jsonld

### ISSUE THREAD

**Issue by kosgobakis** [Fiware/tutorials.Getting-Started#37]
The url [https://uri.fiware.org/ns/data-models](https://uri.fiware.org/ns/data-models) that is the base for the fiware is not accessible 
So the linked data does not work ie.
```
"fiware": "https://uri.fiware.org/ns/data-models#",
"Building": "fiware:Building",
```
-> [https://uri.fiware.org/ns/data-models#Building](https://uri.fiware.org/ns/data-models#Building)

**Comment by jason-fox** [comment]
That is a URI not a URL (well technically that is an IRI in the ETSI spec). Not all URIs resolve to webpages readable by humans. You will find the same issue with some of the URIs within the core `@context`

**Comment by jason-fox** [comment]
This has now been updated to resolve the URI to a URL, but is likely to be changed to reference [Smart Data Models](https://smartdatamodels.org/) in the future
