### ISSUE TITLE
`services` script does not validate

### ISSUE THREAD

**Issue by jze** [Fiware/tutorials.Getting-Started#38]
According to the tutorial the `services` script can be used to validate data models:

```
./services validate [file]
```

However, `services` contained in this repo does not know this command:

```
tutorials.NGSI-LD/tutorials.Getting-Started$ ./services validate
Command not Found.
usage: services [create|orion|scorpio|stellio|stellio|stop]
```

**Comment by jason-fox** [comment]
That command applies to a different tutorial, called [FIWARE/tutorials.Understanding-At-Context](https://github.com/FIWARE/tutorials.Understanding-At-Context/).

In general `create`, `start` and `stop` are common, but the availability other commands will vary based on the needs of the tutorial itself.
