### ISSUE TITLE
In any tutorial add a section on how to represent the same example using JSON-LD (NGSI-LD)

### ISSUE THREAD

**Issue by jmcanterafonseca** [Fiware/tutorials.Getting-Started#4]

**Comment by jason-fox** [comment]
I'm still getting my head around linked data. Are you saying we need an example of a JSON object with an additional `@context` element



So If I have a **Store** response for a response JSON Object like:

```json 
{
    "id": "urn:ngsi-ld:Store:001",
    "type": "Store",
    "address": {
        "streetAddress": "Bornholmer Straße 65",
        "addressRegion": "Berlin",
        "addressLocality": "Prenzlauer Berg",
        "postalCode": "10439"
    },
    "location": {
        "type": "Point",
        "coordinates": [
            13.3986,
            52.5547
        ]
    },
    "name": "Bösebrücke Einkauf"
}
```

Would you be looking for an inline context definition as defined in [Example 5](https://www.w3.org/TR/2014/REC-json-ld-20140116/)

Something like:

```json
{
    "id": "urn:ngsi-ld:Store:001",
    "type": "Store",
    "address": {
        "streetAddress": "Bornholmer Straße 65",
        "addressRegion": "Berlin",
        "addressLocality": "Prenzlauer Berg",
        "postalCode": "10439"
    },
    "location": {
        "type": "Point",
        "coordinates": [
            13.3986,
            52.5547
        ]
    },
    "name": "Bösebrücke Einkauf",
    "@context": {
	    "id" : "@id",
	    "type": "@type",
	    "name": "http://uri.etsi.org/ngsi-ld/name",
	    "address": "http://schema.org/PostalAddress",
	    "location": "http://uri.etsi.org/ngsi-ld/location"
    }
  },
}
```


Which is referring to `name` and `location` from the [ngsi-ld draft](https://docbox.etsi.org/ISG/CIM/Open/ISG_CIM_NGSI-LD_API_Draft_for_public_review.pdf)
and `address` from schema.org.


And  for the **Shelf**  which includes `Relationship` and `Integer` we'd need something like:


```json
{
    "id": "urn:ngsi-ld:Shelf:unit001",
    "type": "Shelf",
    "location": {
        "type": "Point",
        "coordinates": [
            13.3986112,
            52.554699
        ]
    },
    "maxCapacity": 50,
    "name": "Corner Unit",
    "refStore": "urn:ngsi-ld:Store:001",
    "@context": {
	    "id" : "@id",
	    "type": "@type",
	    "location": "http://uri.etsi.org/ngsi-ld/location",
	    "name": "http://uri.etsi.org/ngsi-ld/name",
	    "refStore": {
	    	"@id": "http://uri.etsi.org/ngsi-ld/Relationship",
	    	"@type": "@id"
	    },
	    "maxCapacity": {
	    	"@id": "http://schema.org/Integer",
	    	"@type": "@id"
	    },
	    
    }
}
```

If this is the case it would make more sense to  include it in the **Entity Relationships** tutorial than the **Getting Started**

**Comment by jmcanterafonseca** [comment]
apart from needing a @context, that could be behind a URI,  i.e. probably it is not need to inline the @context, 

NGSI-LD labels attribute nodes as "Property" or "Relationship" and that's a representation difference. There are also differences such as labelling location properties as "GeoProperty", the usage of "unitCode", "observedAt",  etc. 

My proposal would be that each tutorial to have at the end a section, named, representation as NGSI-LD and just encode the entities using that representation format. I agree that in the E-R tutorial it would be more adequate, but I think it would be great to introduce NGSI-LD in each of our tutorials.

**Comment by jason-fox** [comment]
**Closing** as Linked Data concepts are too advanced for a **Hello World** style getting started. 

Separate additional *FIWARE 60x* tutorials will be added to discuss NGSI Linked Data and linked data concepts. The first one is available [here](https://github.com/FIWARE/tutorials.Linked-Data) 

Partially fixed by: https://github.com/FIWARE/tutorials.Step-by-Step/commit/76b452026e3b040adad2e26a529fdfb96fd5ea7f

Additional concepts such as [Linked Data Relationships](https://github.com/jason-fox/tutorials.Relationships-Linked-Data) will be added when available.
