### ISSUE TITLE
Link to import postman collection expired

### ISSUE THREAD

**Issue by ranim-n** [Fiware/tutorials.Getting-Started#45]
I started following this series of tutorials to learn more about NGSI-LD but the link to import the postman collection at the begining has expired.

**Comment by jason-fox** [comment]
Does this link work for you? `https://fiware.github.io/tutorials.Getting-Started/ngsi-ld.html`

A copy of the collection is a available on the `NGSI-LD` branch of the repository.

**Comment by ranim-n** [comment]
Yes, this link works. Thank you
